### ISSUE TITLE
Instructor Feedback - Week 4

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Normnondo/beacon#1]
Looks like you have a great start with hibernate in your indie project!

- [ ] Are all the getUsersBy... methods needed? Would the getbyProperty... methods handle these cases?

**Comment by Normnondo** [comment]
I was focused on completing the exercise, but as I was doing so I realized I probably won't need all of them, I'll try to make adjustments with this week's exercise. Thank you!
