### ISSUE TITLE
Instructor Feedback - Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Normnondo/beacon#2]
Nice job implementing the one to many in your indie project. This will position you well moving forward.

- [x] Time to think about implementing that generic dao. Take a look at Fat Bike Trail Reports for inspiration.
- [ ] Think about adding test to delete a user and verify that games are or are not deleted (depending on your business rules for that situation).

**Comment by Normnondo** [comment]
Generic Dao implemented, will make a new issue for the other item.
