### ISSUE TITLE
Feedback Code Review

### ISSUE THREAD

**Issue by jrshutske** [Normnondo/beacon#41]
Most of the would be feedback was being taken care of last night and is already stored in tickets on the project. The only thing that we came to a conclusion on is to test more of the controller methods. Since they were written inside of the doGet methods we will be unable to test them without first breaking the logic out into its own method.

Aside from that the structure of the project looks good. It looks like you've gotten really good at organizing your project into understandable classes and organizing your work into bite-sized issues. The code itself was very easy to read and understand. Once you add you Java Docs it will be a good project for people to jump in on and contribute.

**Comment by pawaitemadisoncollege** [comment]
Which code quality tool did you use to analyze? Include a screenshot here of the findings for easy comparison after the changes are made.

**Comment by Normnondo** [comment]
Thank you for the feedback.  Closing this issue for now to keep my issues clean.

**Comment by jrshutske** [comment]
Hopefully this won't re-open the issue. We used QAPlug's findbugs, checkstyle. @pawaitemadisoncollege
